apiVersion: v1
kind: ConfigMap
metadata:
  name: aksdeploysvc-config
  namespace: sample-app-namespace-1774550555471
  labels:
    app.kubernetes.io/name: aksdeploysvc
    kubernetes.azure.com/generator: devhub
data: