apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: main
  labels:
    app.kubernetes.io/name: main
    app.kubernetes.io/part-of: main-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: main