apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aksdeploysvc
  labels:
    app.kubernetes.io/name: aksdeploysvc
    app.kubernetes.io/part-of: aksdeploysvc-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aksdeploysvc